settings:
  cache_path: ".zeno_cache02"
  host: 0.0.0.0
  port: 8666

data:
  data_path: "data/sample_product_data.csv"
  sample_size: 10
  data_column: "product_name"

models:
  - "gpt-4o-mini"

prompt:
  task_description: "Generate catchy taglines for new products"
  requirements:
    - name: "tagline-length"
      description: "Each tagline should be 10 words or fewer."
      priority: "hard"
      category: "content"
      feature: "conciseness"
    # - name: "short-options"
    #   description: "Each answer option is less than 10 words."
    #   priority: "soft"
    #   category: "content"
    #   feature: "clarity-to-student"
    # - name: "answer-format"
    #   description: "EThe answer options are ordered in (A) (B) (C) (D)."
    #   priority: "hard"
    #   category: "presentation"
    #   feature: "clarity-to-student"
    # - name: "correct-answer"
    #   description: "The correct answer is included after the answer options."
    #   priority: "hard"
    #   category: "content"
    #   feature: "grading-for-teacher"
    # - name: "correct-answer-justification"
    #   description: "Provide a justification for the correct answer."
    #   priority: "hard"
    #   category: "content"
    #   feature: "grading-for-teacher"
