settings:
  cache_path: ".zeno_cache1207"
  host: 0.0.0.0
  port: 8000

data:
  data_path: "data/mmlu.csv"
  sample_size: 30
  data_column: "question"

models:
  - "gpt-4o-mini-2024-07-18"

prompt:
  task_description: ""
  requirements:
    - name: "num-options"
      description: "Write exactly 4 answer options."
    - name: "short-options"
      description: "Each answer option is less than 10 words."
    - name: "answer-format"
      description: "The answer options are ordered in (A) (B) (C) (D)."
    - name: "single-correct-answer"
      description: "There is only one correct answer."
    - name: "correct-answer"
      description: "The correct answer is included after the answer options."
    - name: "correct-answer-justification"
      description: "Provide a justification for the correct answer."
