settings:
  cache_path: ".zeno_cache1230"
  host: 0.0.0.0
  port: 8000
  baseline: true

data:
  data_path: "data/mmlu.csv"
  sample_size: 30
  data_column: "question"

models:
  - "gpt-4o-mini-2024-07-18"

prompt:
  task_description: "Write quiz answer options for the following question."
  requirements:
    - name: "num-options"
      description: "Write exactly 4 answer options."
      priority: "hard"
      category: "content"
      feature: "clarity-to-student"
    - name: "short-options"
      description: "Each answer option is less than 10 words."
      priority: "soft"
      category: "content"
      feature: "clarity-to-student"
    - name: "answer-format"
      description: "The answer options are ordered in (A) (B) (C) (D)."
      priority: "hard"
      category: "presentation"
      feature: "clarity-to-student"
    - name: "single-correct-answer"
      description: "There is only one correct answer."
      priority: "hard"
      category: "content"
      feature: "clarity-to-student"
    - name: "correct-answer"
      description: "The correct answer is included after the answer options."
      priority: "hard"
      category: "structure"
      feature: "grading-for-teacher"
    - name: "correct-answer-justification"
      description: "Provide a justification for the correct answer."
      priority: "hard"
      category: "content"
      feature: "grading-for-teacher"