FROM python:3.10-slim

WORKDIR /app

# Install nvm
RUN apt-get update && \
    apt-get -y install curl
ENV NVM_DIR=/root/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash \
    && . $NVM_DIR/nvm.sh

# Make sure nvm is loaded and install a node version (replace x.x.x with the version you want)
RUN . $NVM_DIR/nvm.sh && nvm install 16.20.1 && nvm use 16.20.1

# Install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

# Install poetry
ENV POETRY_VERSION=1.8.0 
ENV PATH="/root/.local/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION

# Install make
RUN apt-get -y install make


COPY . /app

RUN make install
RUN make localbuild

# Run the server script
CMD ["poetry", "run", "python3", "run.py"]